dist: xenial
language: python

cache: pip

branches:
  only:
    - master

jobs:
  include:
    - stage: Check
      python: 3.7
      install: scripts/install --no-node
      script: scripts/check

    - stage: Test
      python: 3.7
      before_install:
        - nvm install 10
        - nvm use 10
      install: scripts/install
      script:
        - scripts/build
        - scripts/test
      after_script:
        - if [ -f .coverage ]; then
          python -m pip install codecov;
          codecov --required;
          fi
