trigger:
  - master

jobs:
  - job: Check
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: "3.8"
        displayName: "Use Python"

      - script: scripts/install --no-node
        displayName: "Install dependencies"

      - script: scripts/check
        displayName: "Run checks"

  - job: Test
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: "3.8"
        displayName: "Use Python"

      - script: scripts/install --no-node
        displayName: "Install dependencies"

      - script: scripts/test
        displayName: "Run tests"

      - script: bash <(curl -s https://codecov.io/bash)
        displayName: "Upload coverage"
